### ISSUE TITLE
Get discharge for water temp sites

### ISSUE THREAD

**Issue by nehill197** [poissonconsulting/fish-passage-22#12]
[points_to_get_discharge.xlsx](https://github.com/poissonconsulting/fish-passage-22/files/13909035/points_to_get_discharge.xlsx)

**Comment by NewGraphEnvironment** [comment]
As a place to put this.  Climate scenarios explained here:

https://journals.ametsoc.org/view/journals/clim/28/3/jcli-d-14-00636.1.xml?tab_body=pdf

![image](https://github.com/poissonconsulting/fish-passage-22/assets/46538103/b6423209-9be8-43e4-b98b-812d3225a42e)


selected CanESM2 just because it is from Canadian Centre for Climate Modeling and Analysis.  Bonus that it has 5 model contributors

with the help of chatGPT4 and the [PCIC help pages](https://data.pacificclimate.org/portal/docs/raster.html#dataset-selection) used this call to get the URL

```
wget --output-document=- https://data.pacificclimate.org/portal/hydro_model_out/catalog/catalog.json 2> /dev/null | jq -r 'to_entries[] | select(.key | test("BASEFLOW";"i") and test("CanESM2_rcp45";"i")) | .value'

```

`https://data.pacificclimate.org/data/hydro_model_out/allwsbc.CanESM2_rcp45_r1i1p1.1945to2099.BASEFLOW.nc`

same thing in R is 

```
library(jsonlite)
library(stringr)
# Read the JSON data into R
json_data <- fromJSON("https://data.pacificclimate.org/portal/hydro_model_out/catalog/catalog.json")

# Filter the data
filtered_data <- json_data[str_detect(names(json_data), "BASEFLOW") & str_detect(names(json_data), "CanESM2_rcp45")]
```

result is 
```
$`BASEFLOW_day_VICGL_CanESM2_rcp45_r1i1p1_19450101-20991231_columbia`
[1] "https://data.pacificclimate.org/data/hydro_model_out/allwsbc.CanESM2_rcp45_r1i1p1.1945to2099.BASEFLOW.nc"
```

Tried to get some info about the dataset on the cmd line that might help figure out how to describe the bounding box

`wget --output-document=- https://data.pacificclimate.org/portal/hydro_model_out/allwsbc.CanESM2_rcp45_r1i1p1.1945to2099.BASEFLOW.nc 2> /dev/null`
likely because this is not the [Dataset Descriptor Structure](http://docs.opendap.org/index.php/UserGuideOPeNDAPMessages) this is not giving us info about the variables (didn't read the instructions carefully) - but does give info including this little jem:

`bc_basemap_url: 'https://services.pacificclimate.org/tiles/bc-albers-lite/${z}/${x}/${y}.png` 

cool.  

tried modifying to look like the help doc example as so:

`wget --output-document=- https://data.pacificclimate.org/portal/hydro_model_out/catalog/BASEFLOW_day_VICGL_CanESM2_rcp45_r1i1p1_19450101-20991231_columbia.h5.dds 2> /dev/null`

with no result.... Interestingly though the actual help doc call does not return any response either so maybe this is structured correctly (doubt it).  

TBC -  I will ask Norris if he remembers what `[13149:24105]` is in the makefile call to download baseflow data below...

```
curl -o $@ 'https://data.pacificclimate.org/data/hydro_model_out/allwsbc.TPS_gridded_obs_init.1945to2099.BASEFLOW.nc.nc?BASEFLOW'$(printf %s '[13149:24105][][]'|jq -sRr @uri)
```
